server:
  port: ${SERVER_PORT}
logging:
  level:
    root: INFO
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/y-chat-e5132