# In reality, we would also encrypt it and provide integrity protection and of course not store it
# in version control
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: eWNoYXRAeWNoYXQuY29t
  PGADMIN_DEFAULT_PASSWORD: eWNoYXRmb3JtZXJseWtub3duYXM=