# TODO The type probably has to change for it to work on GKE
apiVersion: v1
kind: PersistentVolume
metadata:
  name: social-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"