version: '3'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      TZ: "UTC"
      PGADMIN_DEFAULT_EMAIL: "ychat@ychat.com"
      PGADMIN_DEFAULT_PASSWORD: "ychatformerlyknownas"
      PGADMIN_LISTEN_PORT: "80"
    ports:
      - "55050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
    depends_on:
      - social-db

  social-db:
    image: postgres:latest
    environment:
      TZ: "UTC"
      POSTGRES_DB: "social-db"
      POSTGRES_INITDB_ARGS: "--locale=en_US.utf8"
      POSTGRES_USER: "ychat"
      POSTGRES_PASSWORD: "ychatformerlyknownas"
    ports:
      - "55432:5432"
#    volumes:
#      - ./social-db/social-db-schema.sql:/docker-entrypoint-initdb.d/social-db-schema.sql