package com.ychat.ychat.enums;

public enum NotificationTypeEnum {
    NEW_MESSAGE, UPDATED_MESSAGE, MEDIA_UPLOADED, TRANSACTION_COMPLETE, SIGNALING_NEW_OFFER, SIGNALING_NEW_ANSWER, SIGNALING_NEW_CANDIDATE, CALL_ENDED;
}
