version: '3'

services:
  pgadmin:
    container_name: "ychat-pgadmin"
    image: dpage/pgadmin4:8.2
    environment:
      TZ: "UTC"
      PGADMIN_DEFAULT_EMAIL: "ychat@ychat.com"
      PGADMIN_DEFAULT_PASSWORD: "ychatformerlyknownas"
      PGADMIN_LISTEN_PORT: "80"
    ports:
      - "55050:80"
    volumes:
      - ./social-db/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - social-db

  social-db:
    container_name: "ychat-social-db"
    image: postgres:16.1
    environment:
      TZ: "UTC"
      POSTGRES_DB: "social-db"
      POSTGRES_INITDB_ARGS: "--locale=en_US.utf8"
      POSTGRES_USER: "ychat"
      POSTGRES_PASSWORD: "ychatformerlyknownas"
    ports:
      - "55432:5432"
    volumes:
      - ./social-db/social-db/social-db-1-config.sql:/docker-entrypoint-initdb.d/social-db-1-config.sql
      - ./social-db/social-db/social-db-2-schema.sql:/docker-entrypoint-initdb.d/social-db-2-schema.sql
